### ISSUE TITLE
shallower fails when objects contain anonymous function

### ISSUE THREAD

**Issue by dotnetCarpenter** [othiym23/only-shallow#4]
The culprit is [line 58 in `only-shallow`](https://github.com/othiym23/only-shallow/blob/master/index.js#L58)

My use case is testing Functors using [`tap`](https://github.com/tapjs/node-tap/).

``` js
const plus3 = x => x+3

const fmap = (f, F) => {
  if(F instanceof Nothing) return F
  return F.fmap((f(F.val)))
}
function Just(val) {
  if(this == undefined) return new Just(val)
  this.val = val
  this.fmap = x => new Just(x)
}
function Nothing() {
  if(this == undefined) return new Nothing
  this.fmap = x => new Nothing
}
function Maybe(val) {
  if(val == undefined) return new Nothing
  return new Just(val)
}

tap.same(fmap(plus3, Just(2)), Just(5), "fmap knows how to apply functions to values that are wrapped in a context.")
```

The above fails:

```
TAP version 13
not ok 1 - fmap knows how to apply functions to values that are wrapped in a context.
  ---
  found:
    val: 5
    fmap: x => new Just(x)
  wanted:
    val: 5
    fmap: x => new Just(x)
```

I suggest testing for functions in `shallower_` and do a char by char comparison of function.toString(), similar to `tap.equal("hello", "hello")`

> Ref: https://github.com/tapjs/node-tap/issues/258

**Comment by dotnetCarpenter** [comment]
Since there is a test for referential equal functions, which fails on identical but different functions, I guess my suggestion requires a major release. @othiym23, @isaacs I might want to do a PR, if you think it's a good idea.

**Comment by isaacs** [comment]
I'd argue that maybe what you probably want is `t.like` rather than `t.same`, since those functions actually are not the same function. 

But this is a sticky case right on the edge, for sure, since a matching-but-not-identical OBJECT wouldn't fail the test.

**Comment by dotnetCarpenter** [comment]
As an outsider, I would use `t.strictSame` to assert identical function reference and `t.same` as same function. I didn't see `t.like` but that as well doesn't pass my test. I haven't had time to look into why.
I would like to assert that two functions are the same even though they are created through different call paths. Not sure how I would do a function reference test, given my current implementation. That said, I read the [docs](http://www.node-tap.org/asserts/#tmatchfound-pattern-message-extra) as `t.like` will give me a kind of interface check on an object (but without types) which isn't exactly what I would like.

When I find the time, I will add a passing implementation via `t.addAssert`. Then we can discuss its usefulness.

``` js
const plus3 = x => x+3

// Functors
const fmap = (f, F) => {
  if(F instanceof Nothing) return F
  return F.fmap((f(F.val)))
}
function Just(val) {
  if(!new.target) return new Just(val)
  this.val = val
  this.fmap = x => new Just(x)
}
function Maybe(val) {
  if(val == undefined) return new Nothing
  return new Just(val)
}
function Nothing() {
  if(!new.target) return new Nothing
  this.fmap = x => new Nothing
}
// Tests
tap.like(fmap(plus3, Just(2)), Just(5), "fmap knows how to apply functions to values that are wrapped in a context.")
console.log(
  'fmap(plus3, Just(2))\t-> ',
  fmap(plus3, Just(2))
)
console.log(
  'fmap(plus3, Nothing())\t-> ',
  fmap(plus3, Nothing())
)
```

Output:

```
not ok 1 - fmap knows how to apply functions to values that are wrapped in a context.
  ---
  found:
    val: 5
    fmap: x => new Just(x)
  pattern:
    val: 5
    fmap: x => new Just(x)
  at:
    line: 40
    column: 5
    file: Functor.js
  stack: |
    Object.<anonymous> (Functor.js:40:5)
  source: >
    tap.like(fmap(plus3, Just(2)), Just(5), "fmap knows how to apply functions to
    values that are wrapped in a context.")
  ...
fmap(plus3, Just(2))    ->  Just { val: 5, fmap: [Function] }
fmap(plus3, Nothing())  ->  Nothing { fmap: [Function] }
```

**Comment by othiym23** [comment]
> I would like to assert that two functions are the same even though they are created through different call paths.

In general, this is an _extremely_ hazardous idea, and something I'm unlikely to land into `deeper` or `only-shallow`. You're _much_ better off testing this manually / explicitly.

Here's why: in general, there's no way to assert that two functions are identical in any Turing-complete language that also includes lexical closure. Even were you to verify that two functions had the same name and `fn.toString()` produced identical results, any lexically bound values in the function text (including function invocations) could be pointing to very different things. To prove that they were the "same" function in anything other than the weakest sense would require solving the [halting problem](https://en.wikipedia.org/wiki/Halting_problem), or (heuristically) by having access to and comparing both functions' lexical environments, which JS doesn't allow. (If you're curious or confused, there's a really good discussion of function equality in [_The Little Schemer_](https://mitpress.mit.edu/books/little-schemer), one of my favorite programming books.).

I acknowledge that this is a bummer when you have two objects containing functions as properties that are dynamically-produced closures, but I agree (I think) with @isaacs that using something that allows you to test specifically those bits of the objects you want to match using `t.like` is a better solution in this case.

Thanks for your time and the thorough problem description!

**Comment by isaacs** [comment]
Yeah, putting this in only-shallow or deeper is a bad idea.

The _extremely_ loosey-goosey [tmatch](http://npm.im/tmatch) (which powers `t.like`) gives you a way to test against a pattern in a way that may make you happy, tho:

```
$ cat dub.js
var t = require('tap')
var dub = {dub: x => x * 2 }
t.like(dub, {dub: Function})
t.like(dub, {dub: 'x => x * 2'})

$ node dub.js
TAP version 13
ok 1 - should match pattern provided
ok 2 - should match pattern provided
1..2
# time=38.75ms
```

**Comment by dotnetCarpenter** [comment]
@isaacs I don't get it. Why does `tap.like( fmap( plus3, Just(2) ), Just(5) )` fail then?

```
fmap( plus3, Just(2) -> { val: 5, fmap: Function }
Just(5)              -> { val: 5, fmap: Function }
```

**Comment by isaacs** [comment]
@dotnetCarpenter Because in that case, you're comparing a function to another function, not to the `Function` constructor (which would verify that the thing is a function) or to the string value (which would compare the `toString()`-casted value).
